<?php

// Generated by the framework's container compiler. Not program text: it is
// regenerated from the source above and is absent from a cold checkout.

use Demo\Derived\Support\CachedOnly;

return [
    'services' => [
        'cached_only' => static fn(): CachedOnly => new CachedOnly(),
    ],
];
