<?php

declare(strict_types=1);
/*
 * This file is part of PhpcpdNext.
 *
 * (c) 2026 Luciano Federico Pereira
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LucianoPereira\PhpcpdNext\Presentation;

use function array_sum;
use function count;
use function log;

/**
 * The trained parameters of the confidence ranking: how often each feature
 * bucket was seen under a rater's **Y** (duplicated logic) and under their **N**,
 * over the two preserved precision worksheets.
 *
 * The table below is **counted, not tuned**, and is regenerated by
 * `bench/train-confidence.php` from labels that predate this milestone — 120
 * rated findings across two worksheets, each contributing one observation per
 * rater, so a finding the raters disagreed about contributes one to each class
 * rather than being dropped. Ruling T's derivation standard, applied to a second
 * model: counts over a pinned, recorded label set, never fitted to a gate being
 * passed.
 *
 * ## It ranks. It never filters.
 *
 * Nothing in this package consults the score to decide whether a finding is
 * reported. The score reorders a report and prints beside a finding; every
 * finding is in the report either way, and `ConfidenceRankingTest` asserts the
 * set is unchanged by ranking rather than trusting it. That constraint is the
 * charter's, and it is also what makes shipping a model trained on 116 findings
 * defensible at all: a weak ranking costs a reader some scrolling, where a weak
 * *filter* would cost them a clone.
 *
 * ## Naive Bayes again, and for the same reason
 *
 * The independence assumption is false here, as it was in the retired Stage 0
 * classifier — a long finding is more likely to be cross-file — and it is still
 * the right model,
 * because what this owes a reader is not the last point of accuracy but an
 * account it can be argued with. Every score is a sum of per-feature log-odds,
 * printed on demand, so a reader who disagrees with a ranking can see which
 * bucket did it.
 */
final class ConfidenceModel
{
    /**
     * Observations in each class in the training set: [Y, N].
     *
     * 118 findings of the 120 rated, two rater-labels each. The two that are
     * absent are M4's 019 and 056, whose lead site does not relocate into the
     * pinned tree; both are consensus N, and both are named in the packet rather
     * than quietly dropped.
     */
    public const array TOTALS = [125, 111];

    /**
     * feature => bucket => [Y count, N count].
     *
     * @var array<string, array<string, array{0: int, 1: int}>>
     */
    public const array COUNTS = [
        'lines' => [
            'huge' => [5, 25],
            'large' => [23, 29],
            'medium' => [97, 49],
            'small' => [0, 8],
        ],
        'literal' => [
            'dominant' => [0, 2],
            'high' => [2, 68],
            'low' => [62, 10],
            'medium' => [36, 28],
            'trace' => [25, 3],
        ],
        'scope' => [
            'cross-file' => [29, 27],
            'same-file' => [96, 84],
        ],
        'sites' => [
            'many' => [6, 16],
            'three' => [6, 10],
            'two' => [113, 85],
        ],
    ];

    /**
     * @param array<string, array<string, array{0: int, 1: int}>> $counts
     */
    public function __construct(
        private array $counts = self::COUNTS,
        private int $yes = self::TOTALS[0],
        private int $no = self::TOTALS[1],
    ) {}

    /**
     * The class prior as log-odds. An untrained model has no opinion, which is
     * the safe answer rather than an error: with no counts every term is zero and
     * every finding scores the same, so the report keeps the engine's own order.
     */
    public function prior(): float
    {
        if ($this->yes === 0 || $this->no === 0) {
            return 0.0;
        }

        return log($this->yes / $this->no);
    }

    /**
     * Log-odds contributed by one feature bucket, Laplace-smoothed over the
     * buckets actually observed plus one — so a bucket the training set never
     * produced is scored from the same reserved mass on both sides, which is
     * very close to no opinion at all. The right posture for an unseen shape:
     * this tier ranks on evidence, never on unfamiliarity.
     */
    public function logOdds(string $feature, string $value): float
    {
        $buckets = $this->counts[$feature] ?? null;

        if ($buckets === null || $this->yes === 0 || $this->no === 0) {
            return 0.0;
        }

        $vocabulary = count($buckets) + 1;
        [$yes, $no] = $buckets[$value] ?? [0, 0];

        return log(($yes + 1) / ($this->yes + $vocabulary))
            - log(($no + 1) / ($this->no + $vocabulary));
    }

    /** Log-odds of "duplicated logic" against "not": higher ranks higher. */
    public function score(ConfidenceFeatures $features): float
    {
        return array_sum($this->terms($features));
    }

    /**
     * The per-feature contributions, feature name => nats. They sum to
     * {@see score()}, which is what makes a rank auditable rather than merely
     * obeyed.
     *
     * @return array<string, float>
     */
    public function terms(ConfidenceFeatures $features): array
    {
        $terms = ['prior' => $this->prior()];

        foreach (ConfidenceFeatures::NAMES as $name) {
            $terms[$name] = $this->logOdds($name, $features->values[$name] ?? '');
        }

        return $terms;
    }
}
