#!/usr/bin/env php
<?php

declare(strict_types=1);
/*
 * This file is part of PhpcpdNext.
 *
 * (c) 2026 Luciano Federico Pereira
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

const PHPCPD_MINIMUM_PHP = '8.4.0';

/**
 * Autoloader locations, nearest first: installed as a dependency (this
 * file sits in vendor/bin of the consuming project), then a checkout of
 * phpcpd-next itself.
 */
const PHPCPD_AUTOLOADERS = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

if (version_compare(PHP_VERSION, PHPCPD_MINIMUM_PHP, '<')) {
    fwrite(STDERR, sprintf(
        'phpcpd-next requires PHP %s or later; this is PHP %s (%s).' . PHP_EOL,
        PHPCPD_MINIMUM_PHP,
        PHP_VERSION,
        PHP_BINARY,
    ));

    exit(1);
}

foreach (PHPCPD_AUTOLOADERS as $autoloader) {
    if (is_file($autoloader)) {
        require $autoloader;

        exit((new LucianoPereira\PhpcpdNext\Application())->run($_SERVER['argv']));
    }
}

fwrite(STDERR, 'Dependencies are not installed. Run:' . PHP_EOL . '    composer install' . PHP_EOL);

exit(1);
