<?php

declare(strict_types=1);
/*
 * This file is part of PhpcpdNext.
 *
 * (c) 2026 Luciano Federico Pereira
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LucianoPereira\PhpcpdNext\Tests;

require_once __DIR__ . '/_guard.php';

use function array_map;
use function is_dir;
use function is_file;
use function file_put_contents;
use function mkdir;
use function rmdir;
use function scandir;
use function str_replace;
use function strlen;
use function substr;
use function sys_get_temp_dir;
use function uniqid;
use function unlink;

use LucianoPereira\PhpcpdNext\Util\FileFinder;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * The default exclude set. Cache directories are the reason it exists: a tool
 * cache is adversarial input for reference detection, because it is a dense
 * index of exactly the identifiers being searched for. Scanning one turned a
 * failing gate green on a real project while inflating the run 52x.
 *
 * The other half of the design is that defaults match path SEGMENTS. The
 * existing --exclude is substring-based, and shipping "out" or "dist" with those
 * semantics would silently swallow routes/, layouts/, and anything else that
 * merely contains the letters.
 */
#[CoversClass(FileFinder::class)]
final class FileFinderDefaultsTest extends TestCase
{
    private string $root;

    protected function setUp(): void
    {
        $this->root = sys_get_temp_dir() . '/phpcpd-finder-' . uniqid();

        foreach (['src', 'routes', 'vendor', '.phpstan.cache', 'build', 'bin'] as $directory) {
            mkdir($this->root . '/' . $directory, 0o777, true);
        }

        file_put_contents($this->root . '/src/Kept.php', "<?php\nclass Kept {}\n");
        file_put_contents($this->root . '/routes/web.php', "<?php\n// 'routes' contains the default 'out'\n");
        file_put_contents($this->root . '/vendor/Dependency.php', "<?php\nclass Dependency {}\n");
        file_put_contents($this->root . '/.phpstan.cache/resultCache.php', "<?php\nreturn ['Demo\\\\Thing'];\n");
        file_put_contents($this->root . '/build/Artifact.php', "<?php\nclass Artifact {}\n");
        file_put_contents($this->root . '/src/Machine.php', "<?php\n// @generated by a code generator, do not edit\nclass Machine {}\n");
        file_put_contents($this->root . '/bin/console', "#!/usr/bin/env php\n<?php\nnew Kept();\n");
    }

    protected function tearDown(): void
    {
        $this->remove($this->root);
    }

    /** Recursive delete without shelling out, so the suite needs no exec(). */
    private function remove(string $path): void
    {
        if (is_dir($path)) {
            foreach (scandir($path) ?: [] as $entry) {
                if ($entry !== '.' && $entry !== '..') {
                    $this->remove($path . '/' . $entry);
                }
            }

            rmdir($path);

            return;
        }

        if (is_file($path)) {
            unlink($path);
        }
    }

    #[Test]
    public function cache_and_dependency_trees_are_pruned_by_default(): void
    {
        $found = $this->find();

        self::assertNotContains('vendor/Dependency.php', $found);
        self::assertNotContains('.phpstan.cache/resultCache.php', $found);
        self::assertNotContains('build/Artifact.php', $found);
    }

    #[Test]
    public function a_default_matches_a_path_segment_not_a_substring(): void
    {
        // 'routes' contains 'out'; a substring default would eat the directory.
        self::assertContains('routes/web.php', $this->find());
    }

    #[Test]
    public function no_default_excludes_scans_everything(): void
    {
        $found = $this->find(defaults: false);

        self::assertContains('vendor/Dependency.php', $found);
        self::assertContains('.phpstan.cache/resultCache.php', $found);
    }

    #[Test]
    public function a_generated_file_is_skipped_wherever_it_lives(): void
    {
        self::assertNotContains('src/Machine.php', $this->find());
        self::assertContains('src/Kept.php', $this->find());
    }

    #[Test]
    public function a_generated_file_comes_back_when_defaults_are_off(): void
    {
        self::assertContains('src/Machine.php', $this->find(defaults: false));
    }

    #[Test]
    public function an_extensionless_php_entry_point_is_scanned(): void
    {
        // Console entry points are conventionally extensionless, and are exactly
        // where an application's top-level wiring lives.
        self::assertContains('bin/console', $this->find());
    }

    #[Test]
    public function a_file_without_a_php_shebang_is_still_filtered_by_suffix(): void
    {
        file_put_contents($this->root . '/bin/readme', "just some notes\n");

        self::assertNotContains('bin/readme', $this->find());
    }

    /** @return list<string> */
    private function find(bool $defaults = true): array
    {
        $files = (new FileFinder())->find([$this->root], ['.php'], [], $defaults);

        return array_map(
            fn(string $path): string => str_replace('\\', '/', substr($path, strlen($this->root) + 1)),
            $files,
        );
    }
}
