<?php

declare(strict_types=1);
/*
 * This file is part of PhpcpdNext.
 *
 * (c) 2026 Luciano Federico Pereira
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * Sigil — measured values substituted into prose, and a gate that proves the
 * prose still says what the measurement says.
 *
 * A number typed into a document is a claim with no owner. It was true when
 * someone ran something, and nothing afterwards notices when it stops being
 * true: the paper's speed claim, the walltime table, a corpus file count all
 * drifted that way, and each was found by hand, late, one at a time.
 *
 * So documents do not carry numbers. They carry references, and the value is
 * substituted between the marker and its terminator:
 *
 *     the ratio is <!-- [[ $walltime.php_parser_ratio ]] -->12.74x<!--/-->
 *
 * The syntax is sigilmd's (github.com/lucianofedericopereira/sigilmd), reduced
 * to what a fact table needs and made re-enterable, which is the one thing that
 * generator cannot be: sigilmd renders a source into an output, and this
 * rewrites a committed document in place. That is why a terminator is required
 * where sigilmd needs none — it marks the span a re-render replaces. HTML
 * comments render as nothing, so what a reader sees on GitHub is the value
 * alone.
 *
 *   <!-- [[ $table.key ]] -->value<!--/-->    the string, inserted literally
 *   <!-- [[ @table.key ]] -->...<!--/-->      the value read as a path, and the
 *                                             contents of that file inserted
 *   <!-- [[ $a.b$c.d ]] -->                   references chain by concatenation
 *
 * A marker alone on its line inserts a block; a marker with text before it on
 * the line inserts inline. Facts come from a TOML subset — one key = "value"
 * per line, double quotes, every value a string — generated by
 * bench/collect-facts.php and never edited by hand.
 *
 * This file is the parser and renderer; bench/sigil.php is the command that
 * drives them, and bench/collect-facts.php reuses the parser to carry values
 * forward. Requiring it has no side effects.
 *
 */


/**
 * One reference occurrence in a document.
 *
 * @phpstan-type SigilSpan array{ref: string, start: int, length: int, body: string, block: bool}
 */
final class SigilError extends RuntimeException {}

/**
 * Parse the TOML subset the fact table is written in.
 *
 * Deliberately not a TOML parser. It accepts exactly what collect-facts.php
 * emits, and rejects everything else loudly rather than guessing: a fact table
 * that silently half-parses is worse than one that fails.
 *
 * @return array<string, array<string, string>>
 */
function sigil_parse_facts(string $text, string $origin): array
{
    $tables = [];
    $table  = null;

    foreach (explode("\n", $text) as $number => $raw) {
        $line = trim($raw);

        if ($line === '' || str_starts_with($line, '#')) {
            continue;
        }

        if (preg_match('/^\[([A-Za-z_][A-Za-z0-9_]*)\]$/', $line, $m) === 1) {
            $table = $m[1];

            if (isset($tables[$table])) {
                throw new SigilError(sprintf('%s line %d: table [%s] declared twice', $origin, $number + 1, $table));
            }

            $tables[$table] = [];

            continue;
        }

        if (preg_match('/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"((?:[^"\\\\]|\\\\.)*)"$/', $line, $m) !== 1) {
            throw new SigilError(sprintf('%s line %d: not a key = "value" pair: %s', $origin, $number + 1, $line));
        }

        if ($table === null) {
            throw new SigilError(sprintf('%s line %d: key "%s" before any [table]', $origin, $number + 1, $m[1]));
        }

        if (isset($tables[$table][$m[1]])) {
            throw new SigilError(sprintf('%s line %d: key "%s.%s" set twice', $origin, $number + 1, $table, $m[1]));
        }

        $tables[$table][$m[1]] = stripcslashes($m[2]);
    }

    return $tables;
}

/**
 * A span deliberately not rendered, and the reason it is not.
 *
 *     <!-- [[ frozen: measured 2026-09-06, before the banner fix ]] -->
 *         corpus             files   default   unified
 *         php-parser           342    0.478s    6.090s
 *     <!--/-->
 *
 * Some numbers must not move. A table is the record of one sitting on one
 * machine; re-rendering its cells from today's facts would silently rewrite
 * what was measured into a claim nobody made. The changelog is the same case at
 * scale — its entries were true at a release and stay true about that release.
 *
 * So the rule is not "every number is a reference". It is that no number is
 * unmarked: it is either resolved from the fact table, or frozen with a stated
 * reason a reader can weigh. The reason is mandatory, because "this one is
 * special" without saying why is how the hand-typed numbers got here.
 *
 * A frozen span is also the only way to state a number inside an indented code
 * block, where an HTML comment would render as literal text rather than as
 * nothing — the markers sit on their own lines, outside the block.
 */
function sigil_is_frozen(string $ref): bool
{
    return preg_match('/^frozen\s*:/i', trim($ref)) === 1;
}

/**
 * Resolve one reference — possibly a chain — to the text it stands for.
 *
 * @param array<string, array<string, string>> $facts
 */
function sigil_resolve(string $ref, array $facts, string $root, string $origin): string
{
    if (sigil_is_frozen($ref)) {
        throw new SigilError(sprintf('%s: a frozen span has no value to resolve', $origin));
    }

    /*
     * A trailing `| format` names how the value is written, not what it is.
     *
     * The fact table stores 1000 because that is the number; the sentence around
     * it says "at most 1,000 times across the corpus" because that is English.
     * Without this the gate demanded the document write 1000, which is the tool
     * making the prose worse to suit its own storage — the wrong direction. The
     * value stays canonical in the table and the document says how to render it.
     */
    $format = null;

    if (str_contains($ref, '|')) {
        [$ref, $format] = explode('|', $ref, 2);
        $format         = trim($format);
    }

    if (preg_match_all('/([$@])([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)/', $ref, $parts, PREG_SET_ORDER) === 0) {
        throw new SigilError(sprintf('%s: reference "%s" names nothing', $origin, $ref));
    }

    $consumed = 0;

    foreach ($parts as $part) {
        $consumed += strlen($part[0]);
    }

    if ($consumed !== strlen(trim($ref))) {
        throw new SigilError(sprintf('%s: reference "%s" has text outside its lookups', $origin, $ref));
    }

    $out = '';

    foreach ($parts as [, $sigil, $table, $key]) {
        if (!isset($facts[$table])) {
            throw new SigilError(sprintf('%s: no fact table [%s] (in "%s")', $origin, $table, $ref));
        }

        if (!isset($facts[$table][$key])) {
            throw new SigilError(sprintf('%s: fact table [%s] has no key "%s"', $origin, $table, $key));
        }

        $value = $facts[$table][$key];

        if ($sigil === '@') {
            $path = str_starts_with($value, '/') ? $value : $root . '/' . $value;

            if (!is_file($path)) {
                throw new SigilError(sprintf('%s: @%s.%s points at "%s", which is not a file', $origin, $table, $key, $value));
            }

            $read = file_get_contents($path);

            if ($read === false) {
                throw new SigilError(sprintf('%s: @%s.%s could not read "%s"', $origin, $table, $key, $value));
            }

            $value = rtrim($read, "\n");
        }

        $out .= $value;
    }

    return $format === null ? $out : sigil_format($out, $format, $origin);
}

/**
 * Render a value the way a sentence needs to read it.
 *
 * Deliberately a closed list. A format that silently passed anything through
 * would let a typo become a value nobody could trace back to the table.
 */
function sigil_format(string $value, string $format, string $origin): string
{
    if ($format !== 'thousands') {
        throw new SigilError(sprintf('%s: unknown format "%s" (known: thousands)', $origin, $format));
    }

    if (!is_numeric($value)) {
        throw new SigilError(sprintf('%s: cannot apply "thousands" to a non-numeric value "%s"', $origin, $value));
    }

    $decimals = sigil_decimals($value);

    return number_format((float) $value, $decimals, '.', ',');
}

/**
 * Substitute every reference in a document, returning the rendered text.
 *
 * @param array<string, array<string, string>> $facts
 */
function sigil_render(string $document, array $facts, string $root, string $origin): string
{
    $pattern = '/<!--\s*\[\[\s*(?P<ref>[^\]]*?)\s*\]\]\s*-->(?P<body>.*?)<!--\/-->/s';

    $out = preg_replace_callback(
        $pattern,
        static function (array $m) use ($facts, $root, $origin): string {
            if (sigil_is_frozen($m['ref'])) {
                if (trim((string) preg_replace('/^frozen\s*:/i', '', trim($m['ref']))) === '') {
                    throw new SigilError(sprintf('%s: a frozen span must say why it is frozen', $origin));
                }

                return $m[0];
            }

            $value = sigil_resolve($m['ref'], $facts, $root, $origin);
            $open  = sprintf('<!-- [[ %s ]] -->', trim($m['ref']));

            // A marker alone on its line owns the lines between it and the
            // terminator; one with prose before it owns only the run of text.
            $block = str_contains($m['body'], "\n");

            return $block
                ? $open . "\n" . $value . "\n" . '<!--/-->'
                : $open . $value . '<!--/-->';
        },
        $document,
    );

    if ($out === null) {
        throw new SigilError(sprintf('%s: substitution failed (%s)', $origin, preg_last_error_msg()));
    }

    // An opening marker with no terminator is a silent no-op above, which would
    // let a stale value sit unrendered and pass the gate. Count both and refuse.
    $opens = preg_match_all('/<!--\s*\[\[/', $document);
    $pairs = preg_match_all($pattern, $document);

    if ($opens !== $pairs) {
        throw new SigilError(sprintf('%s: %d reference(s) opened, %d terminated by <!--/-->', $origin, $opens, $pairs));
    }

    return $out;
}

/**
 * The shared span pattern: an opening reference, its rendered body, its
 * terminator.
 */
/**
 * Below this, a number matching a fact value is a coincidence rather than a
 * citation: single digits appear everywhere in prose, and a fact table holding
 * a skip count of 0 would otherwise bind every zero in the document.
 */
/**
 * A number as prose writes one.
 *
 * Two exclusions, both learned by being wrong:
 *
 *   - A comma is admitted only as a thousands separator. Allowing it anywhere
 *     turned "at line 13, below" into the token "13,", reported as a rounding
 *     of 12.74.
 *   - A number preceded by ':' or '-' is the right half of a location or a
 *     range, not a quantity. The README's `Billing.php:12-33 (21 lines)` was
 *     reported as stating the symfony-string file count, which is 33 — in the
 *     BINDING class, the one documented as having no judgement call in it. It
 *     has one. An exact value match is strong evidence and not proof, and the
 *     honest fix was to stop generating the coincidence rather than to widen
 *     the claim.
 *
 * A third failure was structural rather than lexical: value equality alone gets
 * *less* precise as the fact table grows, because every new fact is another
 * integer for unrelated prose to collide with. "117 consensus labels" in a
 * milestone record collided with symfony-console's clone count the moment
 * wall-clock facts were collected. That one is answered by
 * {@see sigil_corroborates()} rather than by freezing each collision as it
 * appears — freezing marks the symptom and leaves the detector guessing, so the
 * next coincidence costs another reader another investigation.
 */
const SIGIL_NUMBER = '/(?<![\w.:-])\d+(?:,\d{3})*(?:\.\d+)?/';

const SIGIL_BINDING_FLOOR = 10;

/**
 * How far apart two spellings may be, in relative terms, and still be one
 * measurement written twice. See {@see sigil_restatements()} for why an
 * absolute rounding window alone reports five coincidences for every finding.
 */
const SIGIL_RESTATEMENT_TOLERANCE = 0.02;

const SIGIL_SPAN = '/<!--\s*\[\[\s*(?P<ref>[^\]]*?)\s*\]\]\s*-->(?P<body>.*?)<!--\/-->/s';

/**
 * Numbers a document states in its own voice, outside any reference.
 *
 * The gate as first written proved every value a document DECLARES is current,
 * and said so honestly — while leaving the larger hole untouched: a number
 * typed as bare prose carries no reference, so it cannot go stale in a way
 * anything notices. That is the failure mode this whole mechanism exists for,
 * and exempting it because it is harder to detect would have been the wrong
 * trade.
 *
 * Two severities, because they carry different certainty:
 *
 *   - `binding` — the number is EXACTLY a value in the fact table, and is large
 *     enough that the coincidence means something. The document is stating a
 *     measured fact in prose, it will rot the next time that measurement moves,
 *     and it must be a reference. This fails the gate.
 *
 *     Values below SIGIL_BINDING_FLOOR are excluded, because a fact table full
 *     of small counts otherwise binds every "0", "1" and "2" in the prose to
 *     whichever key happens to hold that value. The first run of this check
 *     reported a list marker and a sentence's "two" as measured facts. A
 *     one-digit match is a coincidence, not a citation.
 *   - `loose` — every other number. Some are facts nobody has collected yet;
 *     some are section numbers, years, versions and CPU model names that will
 *     never be facts. Listed for triage, never fatal, because a gate that cries
 *     about "PHP 8.5" teaches people to ignore it.
 *
 * @param array<string, array<string, string>> $facts
 * @return list<array{line: int, number: string, severity: string, ref: ?string, text: string}>
 */
function sigil_bare_numbers(string $document, array $facts): array
{
    $aliases = $facts['alias'] ?? [];

    // Blank the rendered spans, preserving line structure, so a value that IS
    // referenced is not then reported as bare.
    $masked = preg_replace_callback(
        SIGIL_SPAN,
        static fn(array $m): string => preg_replace('/[^\n]/', ' ', $m[0]) ?? '',
        $document,
    ) ?? $document;

    $masked = sigil_mask_code($masked);

    /** @var array<string, string> $byValue */
    $byValue = [];

    foreach ($facts as $table => $pairs) {
        foreach ($pairs as $key => $value) {
            // First reference wins, so the report names one owner rather than
            // an arbitrary one from a table iterated in a different order.
            $byValue[$value] ??= sprintf('$%s.%s', $table, $key);
        }
    }

    $out = [];

    foreach (explode("\n", $masked) as $index => $line) {
        if (preg_match_all(SIGIL_NUMBER, $line, $found, PREG_SET_ORDER) === 0) {
            continue;
        }

        foreach ($found as $match) {
            $number = $match[0];
            $plain  = str_replace(',', '', $number);
            $ref    = $byValue[$number] ?? $byValue[$plain] ?? null;

            if ($ref !== null && (float) $plain < SIGIL_BINDING_FLOOR) {
                $ref = null;
            }

            // An equal value is a candidate; a sentence ABOUT the fact is what
            // makes it a citation. See sigil_corroborates().
            if ($ref !== null && !sigil_corroborates($line, $ref, $aliases)) {
                $ref = null;
            }

            $out[] = [
                'line'     => $index + 1,
                'number'   => $number,
                'severity' => $ref === null ? 'loose' : 'binding',
                'ref'      => $ref,
                'text'     => trim($line),
            ];
        }
    }

    return $out;
}

/**
 * Blank out code blocks, preserving line structure.
 *
 * This check is about numbers a document states *in its own voice*, and a code
 * block is not a voice — it is transcribed evidence, a rendered table, a
 * command and its output. The numbers in one belong to whatever produced them.
 *
 * It went unnoticed until two coincided: a WordPress data listing happens to
 * contain a clone spanning 46 lines, and a re-measure happened to make
 * `php_parser_clones` 46 as well. The gate then demanded the listing cite a
 * fact about a different corpus. A coincidence of digits inside quoted output
 * is not a citation waiting to be written.
 *
 * Both Markdown forms: fenced, and indented by four spaces or more.
 */
function sigil_mask_code(string $document): string
{
    $out    = [];
    $fenced = false;

    foreach (explode("\n", $document) as $line) {
        if (preg_match('/^\s*```/', $line) === 1) {
            $fenced = !$fenced;
            $out[]  = $line;

            continue;
        }

        $out[] = $fenced || preg_match('/^ {4,}\S/', $line) === 1
            ? (preg_replace('/[^\n]/', ' ', $line) ?? $line)
            : $line;
    }

    return implode("\n", $out);
}

/**
 * The loose numbers, grouped by value, worst first.
 *
 * A flat list of digits and line numbers is a report someone has to redo by
 * hand: it says a number exists, which was never in doubt, and nothing about
 * whether it matters. What matters is repetition. A value stated once may be a
 * section number or a year; a value stated four times is a fact that has been
 * copied, and the next person to update it will update one copy and leave the
 * rest silently wrong. That is the same failure as a stale reference, minus
 * anything that could notice.
 *
 * So the report ranks by copies, carries the line each one sits on, and says
 * out loud how many singletons it is not showing rather than dropping them
 * quietly.
 *
 * @param list<array{line: int, number: string, severity: string, ref: ?string, text: string}> $bare
 * @return list<array{number: string, count: int, lines: list<int>, texts: list<string>, spellings: list<string>}>
 */
function sigil_group_loose(array $bare): array
{
    /** @var array<string, array{number: string, count: int, lines: list<int>, texts: list<string>, spellings: list<string>}> $groups */
    $groups = [];

    foreach ($bare as $entry) {
        if ($entry['severity'] !== 'loose') {
            continue;
        }

        // Group on the VALUE, not the spelling. "11.9x" and "11.90x" are one
        // measurement written twice, and grouping on the string reported them
        // as two unrelated singletons — which is how both survived a review
        // that was looking for exactly this.
        $key = (string) (float) str_replace(',', '', $entry['number']);

        $groups[$key] ??= ['number' => $entry['number'], 'count' => 0, 'lines' => [], 'texts' => [], 'spellings' => []];
        $groups[$key]['count']++;
        $groups[$key]['lines'][]     = $entry['line'];
        $groups[$key]['texts'][]     = $entry['text'];
        $groups[$key]['spellings'][] = $entry['number'];
    }

    foreach ($groups as $key => $group) {
        $groups[$key]['spellings'] = array_values(array_unique($group['spellings']));
    }

    $out = array_values($groups);

    usort($out, static function (array $a, array $b): int {
        return [$b['count'], (float) str_replace(',', '', $b['number'])]
            <=> [$a['count'], (float) str_replace(',', '', $a['number'])];
    });

    return $out;
}

/**
 * Numbers inside frozen spans — the values prose is most likely to restate.
 *
 * Frozen spans are exempt from being REPORTED, because a recorded measurement
 * is supposed to sit still. That exemption quietly removed them as a source
 * too, which was the wrong half to drop: the prose around a table paraphrases
 * the table, and it is the paraphrase that drifts.
 *
 * @return list<string>
 */
function sigil_frozen_numbers(string $document): array
{
    $out = [];

    if (preg_match_all(SIGIL_SPAN, $document, $spans, PREG_SET_ORDER) === 0) {
        return [];
    }

    foreach ($spans as $span) {
        if (!sigil_is_frozen($span['ref'])) {
            continue;
        }

        if (preg_match_all(SIGIL_NUMBER, $span['body'], $found) > 0) {
            foreach ($found[0] as $number) {
                $out[] = $number;
            }
        }
    }

    return array_values(array_unique($out));
}

/**
 * How many digits a spelling commits to after the point.
 */
function sigil_decimals(string $number): int
{
    $at = strpos($number, '.');

    return $at === false ? 0 : strlen($number) - $at - 1;
}

/**
 * Numbers that look like a rounded restatement of a more precise one nearby.
 *
 * The failure that grouping by value still misses. `26.4%` in one paragraph and
 * `26%` in another are the same measurement at two precisions; so are `38.601s`
 * in a table and `38.6s` in the sentence describing it. Neither pair is equal,
 * so neither groups, and both rot independently: re-measure, update the precise
 * one, and the rounded one stays behind as a quietly different claim.
 *
 * Two conditions, and the second was added because the first alone is useless
 * on integers. "Rounds to it at its own precision" gives a whole-number
 * candidate a +/-0.5 window, which swept up every measurement that happened to
 * land nearby: 8 was reported as rounding 7.512, 3 as rounding 2.509, and a
 * bare 0 as rounding 0.091. None of those is a restatement; they are different
 * numbers that are merely close.
 *
 * So the values must also agree to within SIGIL_RESTATEMENT_TOLERANCE in
 * relative terms, which is what actually distinguishes a paraphrase from a
 * coincidence: 38.601 -> 38.6 is 0.003% and 26.4 -> 26 is 1.5%, while
 * 7.512 -> 8 is 6.5% and 2.509 -> 3 is 20%. The threshold is deliberately
 * conservative and will miss aggressive roundings — 1.46 -> 1.5 is 2.7% and is
 * not reported. Missing one is recoverable; a report of seven findings where
 * five are noise is not, because it gets ignored wholesale.
 *
 * @param list<string> $candidates numbers stated in prose
 * @param list<string> $sources    more precise numbers available to restate
 * @return array<string, string> restatement => the source it appears to round
 */
function sigil_restatements(array $candidates, array $sources): array
{
    $out = [];

    foreach ($candidates as $candidate) {
        $plain    = str_replace(',', '', $candidate);
        $value    = (float) $plain;
        $decimals = sigil_decimals($plain);
        $window   = 0.5 * (10 ** -$decimals);

        foreach ($sources as $source) {
            $sourcePlain = str_replace(',', '', $source);
            $sourceValue = (float) $sourcePlain;

            if ($sourceValue === $value || sigil_decimals($sourcePlain) <= $decimals) {
                continue;
            }

            $relative = $value === 0.0 ? INF : abs($sourceValue - $value) / abs($value);

            if (abs($sourceValue - $value) < $window && $relative < SIGIL_RESTATEMENT_TOLERANCE) {
                $out[$candidate] = $source;

                break;
            }
        }
    }

    return $out;
}

/**
 * Does this sentence talk about the fact whose value it happens to contain?
 *
 * Value equality alone is a coincidence generator, and it gets worse as the
 * fact table grows: every fact added is another integer for unrelated prose to
 * collide with. Two got through before this existed — the README's
 * `Billing.php:12-33` matching a corpus file count of 33, and a milestone
 * record's "117 consensus labels" matching symfony-console's clone count the
 * moment wall-clock facts were collected. Both were reported in the class
 * documented as having no judgement call in it.
 *
 * Freezing each one as it appeared was the wrong answer. It marks the symptom
 * and leaves the detector guessing, so the next coincidence costs another
 * reader another investigation. The fix is to ask the only question that
 * separates a citation from a collision: is the surrounding sentence about this
 * quantity at all?
 *
 * Corroboration is a word from the fact's own name — `symfony_string_files`
 * corroborates on "symfony", "string" or "files" — or from its alias list,
 * because prose does not always use the identifier's words: `postings_cap` is
 * written as "kept at most 1,000 times across the corpus", which shares nothing
 * with either half of its key. Aliases are declared by whoever collects the
 * fact, in the fact table, where the meaning is known.
 *
 * A candidate with no corroboration is not silently dropped — it stays in the
 * advisory list. It is only denied the power to fail the build on a coincidence.
 *
 * @param array<string, string> $aliases
 */
function sigil_corroborates(string $line, string $ref, array $aliases): bool
{
    $key = ltrim($ref, '$@');

    [$table, $name] = array_pad(explode('.', $key, 2), 2, '');

    $words = array_filter(explode('_', $table . '_' . $name), static fn(string $w): bool => strlen($w) > 2);

    foreach (explode(' ', $aliases[$name] ?? '') as $alias) {
        if (strlen($alias) > 2) {
            $words[] = $alias;
        }
    }

    $haystack = strtolower($line);

    foreach ($words as $word) {
        if (str_contains($haystack, strtolower($word))) {
            return true;
        }
    }

    return false;
}
