<?php

declare(strict_types=1);
/*
 * This file is part of PhpcpdNext.
 *
 * (c) 2026 Luciano Federico Pereira
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LucianoPereira\PhpcpdNext;

use function array_keys;
use function array_values;

/**
 * The registry of built-in presets. New frameworks are added here as a single
 * Preset entry — the CLI (--preset), the help text, and the headless facade all
 * read from this one list, so a preset is declared in exactly one place.
 */
final class Presets
{
    /** @return non-empty-array<string, Preset> */
    public static function all(): array
    {
        return [
            'laravel' => new Preset(
                name: 'laravel',
                description: 'Laravel apps: scan app/routes/database/config; skip generated, vendored, and view files.',
                suffixes: ['.php'],
                exclude: [
                    'vendor',
                    'node_modules',
                    'storage',
                    'bootstrap/cache',
                    'public',
                    '*.blade.php',          // Blade templates are not analysable PHP source
                    'database/migrations',  // up()/down() boilerplate is duplicate by design
                    '_ide_helper.php',      // generated by barryvdh/laravel-ide-helper
                    '_ide_helper_models.php',
                ],
                paths: ['app', 'routes', 'database', 'config'],
            ),
        ];
    }

    public static function get(string $name): ?Preset
    {
        return self::all()[$name] ?? null;
    }

    /** @return non-empty-list<non-empty-string> */
    public static function names(): array
    {
        /** @var non-empty-list<non-empty-string> */
        return array_keys(self::all());
    }

    /** @return list<Preset> */
    public static function list(): array
    {
        return array_values(self::all());
    }
}
